# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

limits:
  kube-janitor:
    limits:
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 256Mi

# name of instance, will be used to prefix namespaces
instance: prod

cert:
  email: email@example.com
  domain:
    challenges: chal.example.com
