# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kube-janitor:
  quota:
    limits:
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 256Mi

challenge-manager:
  replicas: 3
  authSecret: keyboard-cat
  containerSecret: keyboard-cat
  registryPrefix: ghcr.io/downunderctf
  redis:
    host: ""
    auth: ""
    ca: ""
    db: 0
  oidc:
    serverUrl: ""
    ownerIdField: "noctf.dev/team_id"
    clientId: ""
  quota:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 256Mi
  ui_quota:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 256Mi

landing:
  replicas: 3
  quota:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 0m
      memory: 256Mi

domain:
  challenges: chal.example.com
  isolated: iso.example.com
  management: management.example.com

# google project ID
registries:
  infra: australia-southeast-1-docker.pkg.dev/example/infra
  challenges: australia-southeast-1-docker.pkg.dev/example/challenges

cert:
  email: email@example.com
  cfDNSToken: example

# Don't change these unless you know what you're doing
challengeNamespaces:
  - challenges
  - challenges-isolated
