# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kube-janitor:
  quota:
    limits:
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 256Mi

challenge-manager:
  replicas: 3
  authSecret: keyboard-cat
  containerSecret: keyboard-cat
  registryPrefix: ghcr.io/downunderctf
  quota:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 125m
      memory: 256Mi

landing:
  replicas: 3
  quota:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi

domain:
  challenges: chal.example.com
  management: management.example.com

# google project ID
googleProject: example
googleRegion: australia-southeast1
googleRepositoryName: example

cert:
  email: email@example.com
  cfDNSToken: example

# Don't change these unless you know what you're doing
challengeNamespaces:
  - challenges
  - challenges-isolated
