apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert-challenges
  namespace: traefik
  labels:
    app.kubernetes.io/name: kube-ctf
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  secretName: {{ .Release.Name }}-cert-challenges
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Release.Name }}-letsencrypt
  dnsNames:
  - {{ .Values.domain.challenges }}
  - "*.{{ .Values.domain.challenges }}"