apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kube-ctf-{{ .instance }}-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .cert.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-cert-manager
            key: api-token