{{- $deployment := (index .Values "challenge-manager") }}
apiVersion: v1
kind: Secret
metadata:
  name: challenge-manager-custom-ca
  namespace: {{ .Release.Name }}-management
type: Opaque
data:
  CACHEDIR.TAG: ""
{{- if $deployment.redis.ca }}
  redis.pem: {{ $deployment.redis.ca | b64enc | quote }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-manager
  namespace: {{ .Release.Name }}-management
  labels:
    kube-ctf.downunderctf.com/service: challenge-manager
spec:
  replicas: {{ $deployment.replicas }}
  selector:
    matchLabels:
      kube-ctf.downunderctf.com/service: challenge-manager
  template:
    metadata:
      labels:
        kube-ctf.downunderctf.com/service: challenge-manager
    spec:
      serviceAccountName: challenge-manager
      {{- if $deployment.redis.ca }}
      volumes:
        - name: custom-ca
          secret:
            secretName: challenge-manager-custom-ca
      {{- end }}
      containers:
        - name: challenge-manager
          image: {{ .Values.registries.infra }}/services/challenge-manager:latest
          {{- if $deployment.redis.ca }}
          volumeMounts:
            - name: custom-ca
              mountPath: /ssl/
              readOnly: true
          {{- end }}
          readinessProbe:
            httpGet:
              port: 3000
              path: /healthz
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 3000
              path: /healthz
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: KUBECTF_BASE_DOMAIN
              value: {{ .Values.domain.isolated }}
            - name: KUBECTF_API_DOMAIN
              value: instancer.{{ .Values.domain.management }}
            - name: KUBECTF_NAMESPACE
              value: {{ .Release.Name }}-challenges-isolated
            - name: KUBECTF_MAX_OWNER_DEPLOYMENTS
              value: "4"
            - name: KUBECTF_REGISTRY_PREFIX
              value: {{ $deployment.registryPrefix }}
            - name: KUBECTF_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: challenge-manager
                  key: auth
            - name: KUBECTF_CONTAINER_SECRET
              valueFrom:
                secretKeyRef:
                  name: challenge-manager
                  key: container
          {{- if $deployment.redis.host }}
          {{- $redis := (index $deployment "redis") }}
            - name: REDIS_URL
              value: "redis{{ if $redis.ca }}s{{ end }}://{{ if $redis.auth }}:{{ $redis.auth }}@{{ end }}{{ $redis.host }}/{{ $redis.db }}"
          {{- if $redis.ca }}
            - name: NODE_EXTRA_CA_CERTS
              value: "/ssl/redis.pem"    
          {{- end }}      
          {{- end }}
          
          {{- if $deployment.oidc.serverUrl }}
            - name: OIDC_SERVER_URL
              value: {{ $deployment.oidc.serverUrl }}
            - name: OIDC_OWNER_ID_FIELD
              value: {{ $deployment.oidc.ownerIdField }}
            - name: OIDC_CLIENT_ID
              value: {{ $deployment.oidc.clientId }}
          {{- end }}
          resources:
{{ toYaml $deployment.quota | indent 12 }}
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-manager
  namespace: {{ .Release.Name }}-management
  labels:
    kube-ctf.downunderctf.com/service: challenge-manager
spec:
  selector:
    kube-ctf.downunderctf.com/service: challenge-manager
  ports:
    - port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: challenge-manager-strip-api-prefix
  namespace: {{ .Release.Name }}-management
spec:
  stripPrefix:
    prefixes:
      - /api
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: challenge-manager
  namespace: {{ .Release.Name }}-management
  labels:
    kube-ctf.downunderctf.com/service: challenge-manager
spec:
  entryPoints:
    - websecure
  tls:
    secretName: {{ .Release.Name }}-cert-management
  routes:
    - match: Host(`instancer.{{ .Values.domain.management }}`) && PathPrefix(`/api/`)
      kind: Rule
      priority: 10
      middlewares:
        - name: hsts
        - name: challenge-manager-strip-api-prefix
      services:
        - name: challenge-manager
          port: 3000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: challenge-manager
  namespace: {{ .Release.Name }}-management
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: challenge-manager
  namespace: {{ .Release.Name }}-challenges-isolated
rules:
  - apiGroups:
      - "*"
    resources:
      - ingresses
      - ingressroutes
      - ingressroutetcps
      - pods
      - deployments
      - services
      - namespaces
      - secrets
      - networkpolicies
      - configmaps
      - tlschallenges
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-read-isolated-challenges
rules:
  - apiGroups:
      - kube-ctf.downunderctf.com
    resources:
      - isolated-challenges
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: challenge-manager
  namespace: {{ .Release.Name }}-challenges-isolated
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: challenge-manager
subjects:
- kind: ServiceAccount
  name: challenge-manager
  namespace: {{ .Release.Name }}-management
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-challenge-manager-read-isolated-challenges
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-read-isolated-challenges
subjects:
- kind: ServiceAccount
  name: challenge-manager
  namespace: {{ .Release.Name }}-management
---
apiVersion: v1
kind: Secret
metadata:
  name: challenge-manager
  namespace: {{ .Release.Name }}-management
data:
  auth: "{{ b64enc (index .Values "challenge-manager").authSecret }}"
  container: "{{ b64enc (index .Values "challenge-manager").containerSecret }}"
