apiVersion: v1
kind: Namespace
metadata:
  name: kube-ctf-{{ .instance }}-admin
  labels:
    app.kubernetes.io/name: kube-ctf
    app.kubernetes.io/instance: kube-ctf-{{ .instance }}
    app.kubernetes.io/component: admin
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-ctf-{{ .instance }}-challenges
  labels:
    app.kubernetes.io/name: kube-ctf
    app.kubernetes.io/instance: kube-ctf-{{ .instance }}
    app.kubernetes.io/component: challenges
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-ctf-{{ .instance }}-challenges-isolated
  labels:
    app.kubernetes.io/name: kube-ctf
    app.kubernetes.io/instance: kube-ctf-{{ .instance }}
    app.kubernetes.io/component: challenges