apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Name }}-admin
  labels:
    app.kubernetes.io/name: kube-ctf
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: admin
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Name }}-challenges
  labels:
    app.kubernetes.io/name: kube-ctf
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: challenges
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Name }}-challenges-isolated
  labels:
    app.kubernetes.io/name: kube-ctf
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: challenges