steps:
- id: build
  name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/services/challenge-manager
  - --cache=true
  - --cache-ttl=168h
#  - --context=dir://services/challenge-manager