steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - $LOCATION-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/services/challenge-manager
      - "."
  - id: push
    name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - $LOCATION-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/services/challenge-manager

substitutions:
  _REPOSITORY: 'infra'