apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: kube-janitor
    version: v20.10.0
    role: ctf-system
  name: kube-janitor
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-janitor
  template:
    metadata:
      labels:
        application: kube-janitor
        version: v20.10.0
        role: ctf-system
    spec:
      serviceAccountName: kube-janitor
      containers:
      - name: janitor
        # see https://github.com/hjacobs/kube-janitor/releases
        image: hjacobs/kube-janitor:20.10.0
        args:
          - --interval=120
          - --rules-file=/config/rules.yml
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 20m
            memory: 256Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
          - name: config-volume
            mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: kube-janitor
